#!/usr/bin/env python3

import argparse
import feedparser
import time

URL = 'https://www.archlinux.org/feeds/news/'

parser = argparse.ArgumentParser(description='Read ArchLinux news.')
parser.add_argument('-s', '--show', metavar='n', type=int,
                    help='Show feed [n].')

def main(args=None):
    args = parser.parse_args(args)

    n = 1

    for entry in feedparser.parse(URL).entries:
        if args.show:
            if n == args.show:
                print (entry.summary_detail.value)
        else:
            print ("[%d] %s" % (n, entry.title))
  
        n += 1

if __name__ == '__main__':
    main()
