=head1 NAME

archnews - Simple ArchLinux news reader

=head1 SYNOPSIS

I<archnews> [I<-h>] [I<n>]

=head1 DESCRIPTION

Print a list of 10 most recent ArchLinux news to stdout, or display a summary
of one of them.

=head1 OPTIONS

Without arguments a list of news is printed.

=over 4

=item I<n>

Show summary of feed [n].

=item B<-h, --help>

Show help message and exit.

=back

=head1 WWW

https://github.com/henkkeli/archnews
